namespace WebAuthn.Net.Services.FidoMetadata.Models.FidoMetadataDecoder;

/// <summary>
///     ECDAA Trust Anchor dictionary
/// </summary>
/// <remarks>
///     <para>
///         <a href="https://fidoalliance.org/specs/mds/fido-metadata-statement-v3.0-ps-20210518.html#ecdaatrustanchor-dictionary">FIDO Metadata Statement - §3.9. EcdaaTrustAnchor dictionary</a>
///     </para>
///     <para>
///         Whenever a party uses this trust anchor for the first time, it must first verify that it was correctly generated by verifying \(s, sx, sy\). See
///         <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for details.
///     </para>
/// </remarks>
public class EcdaaTrustAnchor
{
    /// <summary>
    ///     Constructs <see cref="EcdaaTrustAnchor" />.
    /// </summary>
    /// <param name="x">base64url encoding of the result of ECPoint2ToB of the ECPoint2 \(X = P_2^x\). See <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for the definition of ECPoint2ToB.</param>
    /// <param name="y">base64url encoding of the result of ECPoint2ToB of the ECPoint2 \(Y = P_2^y\). See <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for the definition of ECPoint2ToB.</param>
    /// <param name="c">
    ///     base64url encoding of the result of BigNumberToB(\(c\)). See section "Issuer Specific ECDAA Parameters" in <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for an explanation of
    ///     \(c\). See <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for the definition of BigNumberToB.
    /// </param>
    /// <param name="sx">
    ///     base64url encoding of the result of BigNumberToB(\(sx\)). See section "Issuer Specific ECDAA Parameters" in <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for an explanation of
    ///     \(sx\). See <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for the definition of BigNumberToB.
    /// </param>
    /// <param name="sy">
    ///     base64url encoding of the result of BigNumberToB(\(sy\)). See section "Issuer Specific ECDAA Parameters" in <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for an explanation of
    ///     \(sy\). See <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for the definition of BigNumberToB.
    /// </param>
    /// <param name="g1Curve">
    ///     Name of the Barreto-Naehrig elliptic curve for G1. "BN_P256", "BN_P638", "BN_ISOP256", and "BN_ISOP512" are supported. See section "Supported Curves for ECDAA" in
    ///     <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for details.
    /// </param>
    public EcdaaTrustAnchor(
        byte[] x,
        byte[] y,
        byte[] c,
        byte[] sx,
        byte[] sy,
        string g1Curve)
    {
        X = x;
        Y = y;
        C = c;
        Sx = sx;
        Sy = sy;
        G1Curve = g1Curve;
    }

    /// <summary>
    ///     base64url encoding of the result of ECPoint2ToB of the ECPoint2 \(X = P_2^x\). See <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for the definition of ECPoint2ToB.
    /// </summary>
    public byte[] X { get; }

    /// <summary>
    ///     base64url encoding of the result of ECPoint2ToB of the ECPoint2 \(Y = P_2^y\). See <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for the definition of ECPoint2ToB.
    /// </summary>
    public byte[] Y { get; }

    /// <summary>
    ///     base64url encoding of the result of BigNumberToB(\(c\)). See section "Issuer Specific ECDAA Parameters" in <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for an explanation of \(c\). See
    ///     <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for the definition of BigNumberToB.
    /// </summary>
    public byte[] C { get; }

    /// <summary>
    ///     base64url encoding of the result of BigNumberToB(\(sx\)). See section "Issuer Specific ECDAA Parameters" in <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for an explanation of \(sx\). See
    ///     <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for the definition of BigNumberToB.
    /// </summary>
    public byte[] Sx { get; }

    /// <summary>
    ///     base64url encoding of the result of BigNumberToB(\(sy\)). See section "Issuer Specific ECDAA Parameters" in <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for an explanation of \(sy\). See
    ///     <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for the definition of BigNumberToB.
    /// </summary>
    public byte[] Sy { get; }

    /// <summary>
    ///     Name of the Barreto-Naehrig elliptic curve for G1. "BN_P256", "BN_P638", "BN_ISOP256", and "BN_ISOP512" are supported. See section "Supported Curves for ECDAA" in
    ///     <a href="https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html">[FIDOEcdaaAlgorithm]</a> for details.
    /// </summary>
    public string G1Curve { get; }
}
